### PR TITLE
Stationtime

### PR DESCRIPTION
**Pull request by jwebster-LANL**
I edited request.get_stations to 
a) incorporate start/end times for the station search in order to get the correct stations for a given epoch
b) add ability to use wild cards in station search 

Should be tested before merge

### CODE REVIEW

**Comment by cnlg-lanl** [comment]
Have you done much testing with the wildcard functions? Specifically with a station list?  I'm not sure that contains function is going to behave correctly on a list of stations with wildcards included.  Typically I do something like this .filter(or_(*[site.sta.like(stas) for stas in stationlist])) for a wildcard search, but I don't think I've tried the contains before, at least not on a list.

**Comment by jwebster-LANL** [comment]
No, I’m not set up to test pisces right now.

For what it’s worth, that’s what we’ve been doing in infrapy to get around pisces not having that option.  That code is…

  # get station info
    if "%" in stations:
        # Load data specified with a while card (e.g., 'I26H*') via a Site table query
        sta_list = session.query(Site).filter(Site.sta.contains(stations))
    elif ',' in stations:
        # Load data specified by a string list of stations (e.g., 'I26H1, I26H2, I26H3, I26H4') with get_stations
        sta_list = ps.request.get_stations(session, Site, stations=stations.strip('()[]').replace(" ", "").split(','))
    else:
        # Load data specified by a Python list of strings (e.g., ['I26H1', 'I26H2', 'I26H3', 'I26H4']) with get_stations
        sta_list = ps.request.get_stations(session, Site, stations=stations)


It works for us, but I don’t know about wider use.  That’s why it needs to be tested I think









From: Christine Gammans ***@***.***>
Sent: Thursday, March 16, 2023 1:36 PM
To: LANL-Seismoacoustics/pisces ***@***.***>
Cc: Webster, Jeremy David ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [LANL-Seismoacoustics/pisces] Stationtime (PR #52)


Have you done much testing with the wildcard functions? Specifically with a station list? I'm not sure that contains function is going to behave correctly on a list of stations with wildcards included. Typically I do something like this .filter(or_(*[site.sta.like(stas) for stas in stationlist])) for a wildcard search, but I don't think I've tried the contains before, at least not on a list.

**Comment by cnlg-lanl** [comment]
Do you mind if I make changes to your branch? Those wildcards don't work for me.  I've tried running a station list several different ways, and it doesn't recognize them.  The only way it works for me is passing through a single station with a wildcard.

**Comment by jwebster-LANL** [comment]
Feel free

Sent with BlackBerry Work
(www.blackberry.com)


From: Christine Gammans ***@***.******@***.***>>
Date: Friday, Mar 17, 2023 at 3:48 PM
To: LANL-Seismoacoustics/pisces ***@***.******@***.***>>
Cc: Webster, Jeremy David ***@***.******@***.***>>, Author ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [LANL-Seismoacoustics/pisces] Stationtime (PR #52)


Do you mind if I make changes to your branch? Those wildcards don't work for me. I've tried running a station list several different ways, and it doesn't recognize them. The only way it works for me is passing through a single station with a wildcard.

**Comment by cnlg-lanl** [comment]
So I've reduced the wildcard check use to this line

    if stations:
        q = q.filter(or_(*[Site.sta.like(stas) for stas in stations]))

and it works.  Before I push this, is there any value in adjusting the rest of get_stations to just require a list and add wildcard functionality @jwebster-LANL @jkmacc-LANL

**Comment by cnlg-lanl** [comment]
ok I can push that and the wildcards will work for at least the stations

**Comment by cnlg-lanl** [comment]
I'll go ahead and merge this under a 0.4.1, but I think we will need to take a look at some of this really soon and make some more updates

**Comment by jwebster-LANL** [comment]
***@***.***

From: Christine Gammans ***@***.***>
Sent: Monday, March 27, 2023 5:17 PM
To: LANL-Seismoacoustics/pisces ***@***.***>
Cc: Webster, Jeremy David ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [LANL-Seismoacoustics/pisces] Stationtime (PR #52)


Done.

**Comment by jkmacc-LANL** [comment]
Great work, all!  I'm happy to see this, thank you.  FYI, if you put something like "Closes #51" in your PR description, GitHub will automatically close Issue #51 when the PR is merged.

**Pull request merged**
