### PR TITLE
added sqlalchemy 1.4 support

### PR DESCRIPTION
**Pull request by samuelchodur**
I was able to run all the files under tests with sqlalchemy 1.3 and 1.4, but didn't use the module extensively for anything else.

### CODE REVIEW

**Comment by jkmacc-LANL** [comment]
```python
 _____________________ ERROR collecting tests/test_util.py ______________________
/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sqlalchemy/sql/base.py:1150: in __getattr__
    return self._index[key]
E   KeyError: 'items'

The above exception was the direct cause of the following exception:
tests/test_util.py:14: in <module>
    from pisces.tables.css3 import Sitechan
/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pisces/tables/css3.py:5: in <module>
    class Affiliation(css3.Affiliation):
/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/pisces/schema/util.py:392: in __init__
    cls._attrname = {c.name: a for a, c in list(cls.__mapper__.c.items())}  # {col_name: attr_name}
/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sqlalchemy/sql/base.py:1152: in __getattr__
    util.raise_(AttributeError(key), replace_context=err)
/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sqlalchemy/util/compat.py:198: in raise_
    raise exception
E   AttributeError: items
```
This error looks like a change in iteration behavior in [`Mapper.columns`](https://docs.sqlalchemy.org/en/14/orm/mapping_api.html#sqlalchemy.orm.Mapper.columns), which I think returns a [`ColumnCollection`](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnCollection).  

@samuelchodur Could you please try to change `cls._attrname = {c.name: a for a, c in list(cls.__mapper__.c.items())}` in [`pisces/schema/util.py:392`](https://github.com/samuelchodur/pisces/blob/sa-14-support/pisces/schema/util.py#L392) to something like `cls._attrname = {c.name: c.key for c in cls.__mapper__.columns}` , to see if the error is resolved?  I think the `dict`-like behavior of `__mapper__.c` is not fully understood.  Hopefully, these checks will run again automatically with this change.

Thank you again for this PR!

**Comment by samuelchodur** [comment]
@jkmacc-LANL sorry I wasn't able to get to this, but it looks like you have it 1.4 implemented now.

**Comment by jkmacc-LANL** [comment]
@samuelchodur I don't think the issue is fixed.  I just implemented what you did in a branch I could edit to see if my syntax helps, and I think I'm getting the same errors.  Please feel free to continue on your branch if you have any ideas.  

Thank you again!

**Comment by samuelchodur** [comment]
@jkmacc-LANL Sorry for the confusion. With your suggested change, I was able to run pytest successfully.

**Comment by jkmacc-LANL** [comment]
@samuelchodur Thank you for your work here.  We implemented your changes in a different [PR](#49) so we could test locally before pushing.  May I put your name/handle in our `AUTHORS.rst` for your contributions?

Closed by #49

**Comment by samuelchodur** [comment]
> @samuelchodur Thank you for your work here. We implemented your changes in a different [PR](#49) so we could test locally before pushing. May I put your name/handle in our `AUTHORS.rst` for your contributions?
> 
> Closed by #49

I’d be honored! “Chodur, Samuel”. I hope to have more time to contribute in the future. Thanks for all your hardwork.

**Comment by jkmacc-LANL** [comment]
Done 😄  Thank you again!

**Pull request closed without merging**
